### ISSUE TITLE
Opens in XCode

### ISSUE THREAD

**Issue by thedamon** [maguay/Alfred-Plain-Text-Note#1]
Tried out the workflow and it opened the new note in XCode instead of iaWriter (which I do have installed). Running on Yosemite.

**Comment by maguay** [comment]
@thedamon The file will open in the app you have set as default for .md files. If you want to open the files in another app, find a Markdown file in Finder, tap CMD+I to open the file properties pane, and pick the default app you want to use for all Markdown files.
